### ISSUE TITLE
Лицензирование

### ISSUE THREAD

**Issue by drdaemos** [DanielVartanov/encounter-engine#14]
Здравствуйте.
Мне понравился этот проект и я планирую взять ваш код движка за основу, однако планирую переписать некоторые вещи (как минимум, переехать на Rails 5.1 и SPA фронтенд). Есть проблема с правильным лицензированием кода - в данном репозитории нет указания конкретной лицензии (файла LICENSE, как минимум), хотя есть пометка:
> Открытый код (open source). Участники сообщества должны иметь возможность улучшать движок, исправлять баги и уязвимости даже если первоначальные авторы перестанут заниматься разработкой.

По-умолчанию, права на использование и модификацию целиком остаются за автором (подробнее: https://choosealicense.com/no-license/). Прошу рассмотреть данную проблему и указать ту лицензию, которую вы считаете правильной (к примеру - [MIT](https://choosealicense.com/licenses/mit) или [LGPL](https://choosealicense.com/licenses/lgpl-3.0/)).

**Comment by DanielVartanov** [comment]
Доброго дня!

Однозначно приветствую такие начинания, я немедленно добавлю лицению, форкайте на здоровье, и удачи в реализации :)

**Comment by drdaemos** [comment]
Отлично, спасибо за такую быструю реакцию!
